include(":Clone")
include(":image-core")
include(":data-core")
include(":CaldremchX")
include(":utils")
include(":common")
include(":widget")
include(":dialog")
rootProject.name = "Laboratory"
include(":app")
include(":PickerView")
include(":maven-publish-example")
