include(":clone")
include(":image-core")
include(":data-core")
include(":caldremchx")
include(":utils")
include(":common")
include(":widget")
include(":dialog")
rootProject.name = "Laboratory"
include(":app")
include(":PickerView")
